import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MiniUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("openid", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("nickname", models.CharField(blank=True, max_length=80)),
                ("avatar_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("birth_time", models.TimeField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("zodiac", models.CharField(blank=True, max_length=30)),
                ("element", models.CharField(blank=True, max_length=30)),
                ("intention", models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("material_type", models.CharField(choices=[("bead", "Bead"), ("accessory", "Accessory"), ("incense_bead", "Incense Bead"), ("flower_cap", "Flower Cap")], max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("image_url", models.URLField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("diameter_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("element", models.CharField(blank=True, max_length=30)),
                ("energy_tags", models.JSONField(blank=True, default=list)),
                ("effects", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["material_type", "sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=160)),
                ("scene", models.CharField(blank=True, max_length=80)),
                ("image_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("materials", models.JSONField(blank=True, default=list)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("popularity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["-popularity", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receiver", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=32)),
                ("province", models.CharField(max_length=80)),
                ("city", models.CharField(max_length=80)),
                ("district", models.CharField(blank=True, max_length=80)),
                ("detail", models.CharField(max_length=240)),
                ("is_default", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="crystal.miniuser")),
            ],
            options={"ordering": ["-is_default", "-updated_at"]},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("selected", models.BooleanField(default=True)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crystal.material")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cart_items", to="crystal.miniuser")),
            ],
        ),
        migrations.CreateModel(
            name="CrystalAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("intention", models.CharField(max_length=80)),
                ("energy_profile", models.JSONField(blank=True, default=dict)),
                ("recommended_materials", models.JSONField(blank=True, default=list)),
                ("bracelet_plan", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="crystal.miniuser")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DailyEnergy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("lucky_color", models.CharField(blank=True, max_length=40)),
                ("lucky_crystal", models.CharField(blank=True, max_length=80)),
                ("affirmation", models.CharField(blank=True, max_length=180)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("recommended_materials", models.JSONField(blank=True, default=list)),
                ("source", models.JSONField(blank=True, default=dict)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_energies", to="crystal.miniuser")),
            ],
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="DIYPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("intention", models.CharField(blank=True, max_length=80)),
                ("wrist_size_cm", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("beads", models.JSONField(blank=True, default=list)),
                ("accessories", models.JSONField(blank=True, default=list)),
                ("layout", models.JSONField(blank=True, default=dict)),
                ("price_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("cover_image_url", models.URLField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("saved", "Saved"), ("ordered", "Ordered")], default="saved", max_length=20)),
                ("remark", models.TextField(blank=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="diy_plans", to="crystal.miniuser")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_type", models.CharField(max_length=40)),
                ("target_id", models.PositiveIntegerField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="favorites", to="crystal.miniuser")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Inspiration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField(blank=True)),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("materials", models.JSONField(blank=True, default=list)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("collects_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="crystal.miniuser")),
            ],
            options={"ordering": ["-is_featured", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("making", "Making"), ("shipped", "Shipped"), ("done", "Done"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("items", models.JSONField(blank=True, default=list)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("logistics", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("diy_plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="crystal.diyplan")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="crystal.miniuser")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(fields=("user", "target_type", "target_id"), name="unique_favorite"),
        ),
        migrations.AddConstraint(
            model_name="dailyenergy",
            constraint=models.UniqueConstraint(fields=("user", "date"), name="unique_daily_energy_user_date"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(fields=("user", "material"), name="unique_cart_material"),
        ),
    ]
