import { apiRequest } from '@/api/client'

export interface AdminUser { user_id: string; nickname?: string; avatar_url?: string; phone_number?: string; source?: string; profile_status: string; profile_status_text: string; energy_tags: string[]; spend_level: string; spend_level_text: string; paid_amount: number; order_count: number; created_at?: string; updated_at?: string }
export interface UserDetail { user: AdminUser; stats: { order_count: number; paid_amount: number; design_count: number; assessment_count: number }; energy: { tags: string[]; energy_profile: Record<string, number> }; assessments: Array<{ assessment_id: string; core_wish?: string; summary?: string; created_at?: string }>; daily_energies: Array<{ energy_date?: string; title?: string; score?: number; lucky_color?: string; recommended_stone?: string }>; orders: Array<{ order_id: string; status?: string; total_amount?: number; created_at?: string }>; designs: Array<{ design_id: string; status?: string; updated_at?: string }> }
export function listUsers(query: { keyword: string; profileStatus: string; energyTag: string; spendLevel: string; startDate: string; endDate: string }, signal?: AbortSignal): Promise<AdminUser[]> { const p = new URLSearchParams({ keyword: query.keyword, profile_status: query.profileStatus, energy_tag: query.energyTag, spend_level: query.spendLevel, start_date: query.startDate, end_date: query.endDate, limit: '200' }); return apiRequest(`/api/v1/admin/users?${p}`, { signal }) }
export function getUser(userId: string, signal?: AbortSignal): Promise<UserDetail> { return apiRequest(`/api/v1/admin/users/${encodeURIComponent(userId)}`, { signal }) }
export interface Assessment { assessment_id: string; user_id: string; name?: string; core_wish?: string; summary?: string; created_at?: string; updated_at?: string; final_energy_profile?: Record<string, number>; conversion?: { text?: string; status?: string; amount?: number }; formula?: { tags?: Array<{ role?: string; name?: string }> } }
export interface DailyEnergy { energy_date: string; user_id: string; mode?: string; title?: string; score?: number; lucky_color?: string; recommended_stone?: string }
export interface Checkin { checkin_date: string; user_id: string; mood?: number; sleep?: number; stress?: number; updated_at?: string }
export interface AssessmentDetail extends Assessment { input_summary: Record<string, unknown>; energy: { profile: Record<string, number>; breakdown: Record<string, Record<string, number>>; strongest_element?: string; weakest_element?: string; keywords: unknown[]; seasonal: Record<string, unknown>; interpretation?: string }; recommendation: { copy?: string; primary_crystal: Record<string, unknown>; supporting_crystals: Array<Record<string, unknown>>; bracelet_plan: Record<string, unknown>; care_tips: string[]; disclaimer?: string } }
export interface DailyEnergyDetail extends DailyEnergy { assessment_id?: string; updated_at?: string; energy_profile: Record<string, number>; keywords: unknown[]; advice?: string; lucky_time?: string }
export interface CheckinDetail extends Checkin { created_at?: string }
export function listAssessments(query: { keyword: string; wish: string; hideTests: boolean }, signal?: AbortSignal): Promise<Assessment[]> { const p = new URLSearchParams({ keyword: query.keyword, core_wish: query.wish, hide_tests: String(query.hideTests), limit: '200' }); return apiRequest(`/api/v1/admin/assessments?${p}`, { signal }) }
export function listDailyEnergies(keyword: string, signal?: AbortSignal): Promise<DailyEnergy[]> { return apiRequest(`/api/v1/admin/daily-energies?${new URLSearchParams({ keyword, limit: '200' })}`, { signal }) }
export function listCheckins(keyword: string, signal?: AbortSignal): Promise<Checkin[]> { return apiRequest(`/api/v1/admin/checkins?${new URLSearchParams({ keyword, limit: '200' })}`, { signal }) }
export function getAssessmentDetail(assessmentId: string, signal?: AbortSignal): Promise<AssessmentDetail> { return apiRequest(`/api/v1/admin/assessments/${encodeURIComponent(assessmentId)}`, { signal }) }
export function getDailyEnergyDetail(userId: string, energyDate: string, signal?: AbortSignal): Promise<DailyEnergyDetail> { return apiRequest(`/api/v1/admin/daily-energies/${encodeURIComponent(userId)}/${encodeURIComponent(energyDate)}`, { signal }) }
export function getCheckinDetail(userId: string, checkinDate: string, signal?: AbortSignal): Promise<CheckinDetail> { return apiRequest(`/api/v1/admin/checkins/${encodeURIComponent(userId)}/${encodeURIComponent(checkinDate)}`, { signal }) }
export interface DailyRules { rules: Record<string, unknown>; rules_version?: string; public_options?: { rules_version?: string }; updated_at?: string }
export function getDailyRules(signal?: AbortSignal): Promise<DailyRules> { return apiRequest('/api/v1/admin/daily-energy-rules', { signal }) }
export function saveDailyRules(rules: Record<string, unknown>, resetToDefault = false): Promise<DailyRules> { return apiRequest('/api/v1/admin/daily-energy-rules', { method: 'PUT', body: JSON.stringify({ rules, reset_to_default: resetToDefault }) }) }
export interface ManagedAdmin { admin_id: string; username: string; display_name: string; role: 'admin'|'operator'|'viewer'; status: 'active'|'disabled'; failed_login_count: number; locked_until?: string; last_login_at?: string; last_login_ip?: string; created_at?: string; updated_at?: string }
export interface LoginLog { log_id: string; username: string; success: boolean; reason: string; ip?: string; user_agent?: string; created_at?: string }
export interface SystemStatus { checks: Array<{ key:string; label:string; ready:boolean; hint:string }>; ready_count:number; total_count:number }
export interface AdminAccountInput { username?: string; display_name: string; role: ManagedAdmin['role']; status: ManagedAdmin['status']; password?: string }
export function listAdmins(signal?: AbortSignal):Promise<ManagedAdmin[]> { return apiRequest('/api/v1/admin/admins', { signal }) }
export function createAdmin(input: Required<Pick<AdminAccountInput, 'username'|'password'>> & Omit<AdminAccountInput, 'username'|'password'>):Promise<ManagedAdmin> { return apiRequest('/api/v1/admin/admins', { method: 'POST', body: JSON.stringify(input) }) }
export function updateAdmin(adminId: string, input: Omit<AdminAccountInput, 'username'>):Promise<ManagedAdmin> { return apiRequest(`/api/v1/admin/admins/${encodeURIComponent(adminId)}`, { method: 'PUT', body: JSON.stringify(input) }) }
export function disableAdmin(adminId: string):Promise<ManagedAdmin> { return apiRequest(`/api/v1/admin/admins/${encodeURIComponent(adminId)}`, { method: 'DELETE' }) }
export function listLoginLogs(signal?: AbortSignal):Promise<LoginLog[]> { return apiRequest('/api/v1/admin/login-logs?limit=120', { signal }) }
export function getSystemStatus():Promise<SystemStatus> { return apiRequest('/api/v1/admin/system-status') }
