const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_DIR = path.join(ROOT, 'miniprogram', 'config');
const TARGETS = new Set(['test', 'prod']);

const rawTarget = (process.argv[2] || process.env.MINIPROGRAM_ENV || 'test').trim().toLowerCase();
const target = rawTarget === 'production' ? 'prod' : rawTarget;

if (!TARGETS.has(target)) {
  console.error(`Invalid miniprogram env "${rawTarget}". Use "test" or "prod".`);
  process.exit(1);
}

const sourceFile = path.join(CONFIG_DIR, `env.${target}.js`);
if (!fs.existsSync(sourceFile)) {
  console.error(`Missing config file: ${sourceFile}`);
  process.exit(1);
}

const envFile = path.join(CONFIG_DIR, 'env.js');
const body = [
  '// This file is generated by scripts/select_miniprogram_env.js.',
  `// Active target: ${target}. Do not edit by hand.`,
  `module.exports = require('./env.${target}');`,
  ''
].join('\n');

fs.writeFileSync(envFile, body, 'utf8');

const env = require(sourceFile);
console.log(`miniprogram env=${target}`);
console.log(`api=${env.fallbackBaseUrl}`);
console.log(`assets=${env.assetBaseUrl}`);
